name: app_travel
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_links: ^3.4.1
  http: ^1.1.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/images/

  uses-material-design: true

